### PR TITLE
Add microdata

### PR DESCRIPTION
**Pull request by ghost**
Articles are often used for demos and it's time to improve that simple module in order to fit to Bootstrap (Digital Factory 7.1)

[Review on Reviewable](https://reviewable.io/reviews/jahia/article/1)

### CODE REVIEW

**Comment by pvollenweider** [comment]
A ticket has been open in Jahia ticket system https://jira.jahia.org/browse/QA-7686

**Comment by clement-egger** [comment]
This will be reviewed by R&D in the coming days. Thanks for your commit.

2015-08-07 23:46 GMT+02:00 Fabien Rassinier notifications@github.com:

> Articles are often used for demos and it's time to improve that simple
> 
> ## module in order to fit to Bootstrap (Digital Factory 7.1)
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/Jahia/article/pull/1
> Commit Summary
> - Enable microdata
> - Fix markup
> - Enable microdata support
> - Homogenize EL
> - Fix alt attribute
> - Wrap floats
> - Deal with align
> - Add Bootstrap float support
> 
> File Changes
> - _M_ src/main/resources/jnt_article/html/article.jsp
>   https://github.com/Jahia/article/pull/1/files#diff-0 (30)
> - _M_ src/main/resources/jnt_paragraph/html/paragraph.jsp
>   https://github.com/Jahia/article/pull/1/files#diff-1 (39)
> 
> Patch Links:
> - https://github.com/Jahia/article/pull/1.patch
> - https://github.com/Jahia/article/pull/1.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Jahia/article/pull/1.

## 
- -- --- -----=[ cegger at jahia dot com ]=---- --- -- -
  SVP Product Marketing - Jahia Solutions Group, 9 route des Jeunes CH-1227,
  Carouge (Switzerland)

Jahia is a leading open source User eXperience Platform (UXP) vendor,
relentlessly working at transforming a siloed industry into a user-driven
one, beyond technology constraints - http://www.jahia.com

**Comment by frassinier** [comment]
Thank you guys for the review! 
It was a pleasure to contribute 😂🙌

**Comment by rknj** [comment]
Sorry, I closed this PR because the related ticket was rejected a couple of years ago (without notification here indeed) and there were no updates here.

The reason was that the article view is overriden by default in most of our templates (samples and acme-space-templates). And so they are not using the micro data. The commit was alright but not providing the expected functionalities for all our users, at least not out of the box. Also it is easy to break the rendering with images as there is no constraint for the size.

Feel free to reopen and complete the PR, I will be happy to push this improvement to the Product team.

**Comment by frassinier** [comment]
Thank you for the explanation!
I'll let it closed for these reasons.

**Pull request closed without merging**
